print("K","A","T", sep = ".")
print("K","A","T", sep = "-----")
print("K","A","T", sep = ".", end = "" )
print("Merve")
print("K","A","T", sep = ".", end = ". \n" )
print("Merve", end = "")
print("Merve Çelikkol")